# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.png'
      - 'img/*'
      - 'LICENSE'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.png'
      - 'img/*'
      - 'LICENSE'
      - 'docs/**'

jobs:
  build:

    runs-on: ubuntu-latest
    # See: https://github.com/marketplace/actions/skip-based-on-commit-message
    if: "!contains(github.event.head_commit.message, 'ci skip') || !contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      matrix:
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov
	pip install tabulate --upgrade
	pip install pandas --upgrade
        python setup.py install
    - name: Test with pytest
      run: |
        pytest --cov-report term-missing --cov-config=.coveragerc --cov=requiam tests
    - name: Test scripts
      env:
        pass: ${{ secrets.pass }}
        persist_path: ./
        portal_file: config/portal_manual_template.csv
        quota_file: config/quota_manual_template.csv
      run: |
        ./scripts/script_run --ci --config config/figshare.ini --persistent_path $persist_path --ldap_password $pass --grouper_password $pass --portal_file $portal_file --quota_file $quota_file
        ./scripts/script_run --ci --test --config config/figshare.ini --persistent_path $persist_path --ldap_password $pass --grouper_password $pass --portal_file $portal_file --quota_file $quota_file
        ./scripts/script_run --ci --test_reverse --config config/figshare.ini --persistent_path $persist_path --ldap_password $pass --grouper_password $pass --portal_file $portal_file --quota_file $quota_file
